# Generated by Django 5.2.4 on 2025-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "description_short",
                    models.TextField(blank=True, verbose_name="Короткие описание"),
                ),
                (
                    "description_long",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("latitude", models.FloatField(verbose_name="Широта")),
            ],
        ),
    ]
