# Generated by Django 5.2.4 on 2025-08-04 12:38

from django.db import migrations
import json


def load_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    
    with open('static/places/roofs24.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    Place.objects.create(
        title=data['title'],
        description_short=data['description_short'],
        description_long=data['description_long'],
        longitude=float(data['coordinates']['lng']),
        latitude=float(data['coordinates']['lat']),
    )


def reverse_func(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Place.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_places, reverse_func),
    ]
