# Generated by Django 5.2.4 on 2025-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="serial_number",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AlterField(
            model_name="image",
            name="picture",
            field=models.ImageField(blank=True, upload_to="", verbose_name="Картинка"),
        ),
    ]
