# Generated by Django 5.2.4 on 2025-08-12 15:28

import os
import json
from django.db import migrations, models
from django.core.files.base import ContentFile

import requests


def load_pictures(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Image = apps.get_model('places', 'Image')

    for file in os.listdir('static/places'):
        if file.endswith('.json'):
            with open(os.path.join('static/places', file), 'r', encoding='utf-8') as f:
                data = json.load(f)

            place = Place.objects.get(
                title=data['title']
            )

            for serial_number, img_url in enumerate(data['imgs'], 1):
                response = requests.get(img_url)
                response.raise_for_status()

                filename = os.path.basename(img_url.split("?")[0])

                image = Image(place=place)
                image.serial_number = serial_number
                image.picture.save(filename, ContentFile(response.content), save=True)


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_image"),
    ]

    operations = [
        migrations.AddField(
            model_name='Image',
            name='serial_number',
            field=models.IntegerField("Порядковый номер", default=0),
        ),
        migrations.RunPython(load_pictures),
    ]
