# Generated by Django 5.2.4 on 2025-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_auto_20250814_1557"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
