# Generated by Django 5.2.4 on 2025-08-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_remove_image_serial_number_image_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["serial_number"]},
        ),
        migrations.RemoveField(
            model_name="image",
            name="order",
        ),
        migrations.AddField(
            model_name="image",
            name="serial_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядковый номер"
            ),
        ),
    ]
