# Generated by Django 5.2.4 on 2025-08-18 18:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_image_options_remove_image_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=tinymce.models.HTMLField(
                blank=True, verbose_name="Короткое описание"
            ),
        ),
    ]
