# Generated by Django 5.2.4 on 2025-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_place_description_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
    ]
