# Generated by Django 5.2.4 on 2025-08-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_alter_place_description_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Картинка"
            ),
        ),
    ]
