# Generated by Django 5.2.4 on 2025-08-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="picture",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Место",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["place", "serial_number"], name="places_imag_place_i_5dc488_idx"
            ),
        ),
    ]
