# Generated by Django 5.2.4 on 2025-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0013_alter_image_picture_alter_image_place_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("title", "longitude", "latitude"),
                name="unique_title_coordinates",
            ),
        ),
    ]
